### ISSUE TITLE
Shutdown rsp-server when extension is deactivated

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-adapters#102]
Now when vscode exits rsp-server process exits because it is child process. It should be stopped through shutdown rsp-client call to give server opportunity to save state.

**Comment by adietish** [comment]
+1 on this, I noticed this issue, too.

**Comment by adietish** [comment]
```extension.ts``` shuts the server down afaics:
```
export function deactivate() {
    if (client) client.shutdownServer();
}
```
@dgolovin what am I missing?

**Comment by adietish** [comment]
Closing since this is fixed.
