### ISSUE TITLE
Extension host did not start in 10 seconds, warning message: "it might be stopped on the first line and needs a debugger to continue."

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-adapters#129]
VSCode Version: 1.26.1 (windows 7)

**Comment by mohitsuman** [comment]
@sudhirverma is this happening when you are using the `debug` command for the server ?

**Comment by sudhirverma** [comment]
No, it's happening when I am starting the extension by pressing f5.

**Comment by dgolovin** [comment]
Try `Ctrl+Shift+P`, then type `Select and Start Debugging`. In quick pick select `Extension vscode-adapters`.

**Comment by sudhirverma** [comment]
@dgolovin when I am starting the extension it's not even able to load/start `rsp server`

**Comment by sudhirverma** [comment]
Not working for me on windows 7 reference link https://github.com/Microsoft/vscode/issues/4308

**Comment by dgolovin** [comment]
@sudhirverma  where did you find the solution in #129?

**Comment by dgolovin** [comment]
#130 disable debugging, it is not going to work.

**Comment by sudhirverma** [comment]
there is a similar issue open in vscode https://github.com/Microsoft/vscode/issues/20581
