### ISSUE TITLE
Duplicate server not reported

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-adapters#155]
When you tried to define a new server with an existing id, this is reported by rsp-server that returns a bad status but this is never reported to the UI

**Comment by jeffmaury** [comment]
Blocked by redhat-developer/rsp-client/issues/43

**Comment by jrichter1** [comment]
The UI has a duplicity check for the id input box. How did you manage to get past that, I wonder?

**Comment by jeffmaury** [comment]
Don't know if it's me but existing servers are not retrieved so duplicate is not detected at the UI level. See #157

**Comment by adietish** [comment]
I don't have steps here to verify if things work as expected or not. Nevertheless I tried to create a duplicate server, but couldn't. I thus assume that this bug is outdated. Closing.
