### ISSUE TITLE
felix is not terminated if you exit VSCode

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#159]
Steps:

1) EXEC: launch VSCode with vscode-adapters installed. Activat the extension by opening the "SERVERS" view
2) ASSERT: in terminal list processes and make sure there's a java vm that runs felix:
```
$ ps ax | grep felix
59031   ??  S      0:01.40 /Users/adietish/.jenv/versions/1.8/bin/java -jar /Users/adietish/Documents/jboss-workspaces/vscode-adapters/server/bin/felix.jar
```
3) EXEC: quit VSCode

Result:
felix is still running
```
$ ps ax | grep felix
59031   ??  S      0:01.40 /Users/adietish/.jenv/versions/1.8/bin/java -jar /Users/adietish/Documents/jboss-workspaces/vscode-adapters/server/bin/felix.jar
```

Expected Result:
When VSCode is terminated, the felix should be terminated, too

**Comment by mohitsuman** [comment]
This issue is fixed by #160 . hence closing this issue.
