### ISSUE TITLE
if "select server location" dialog is canceled, promise should be rejected right away

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#200]
this is related to #174.
The fix for that issue removed the warning/error but it actually rejects the promise after trying to look for a server definition. It should do it right ahead when there's no file defined in what one gets from the file dialog.

steps:
1. EXEC: hit "folder" icon in servers view
1. ASSERT: file dialog shows up
1. EXEC: hit "Cancel"

**Comment by dgolovin** [comment]
The fix for #174 works correctly. The reason we are not doing rejection right away, because it would trigger error message. I would not make sense because nothing bad has happened, the user just changed his/her mind and hit `Cancel`.
yes it goes further through Promise chain but does nothing.

**Comment by adietish** [comment]
@dgolovin my PR isn't correct in 2 levels. I suggested a more proper fix but rejected it on things getting more complicated codewise. On the other hand, the current code is convoluted in many levels and we might want to clean it up at a latter moment.
