### ISSUE TITLE
Running state for server should be reflected in deployment running state

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#205]
steps: 

1. ASSERT: have a server started
1. ASSERT: have 1+ deployment that's started
1. EXEC: stop the server

Result:
Server stops and gets "stopped". Deployment(s) are still running.
![image](https://user-images.githubusercontent.com/25126/51530297-eaef5280-1e3a-11e9-92b3-49e3cc9b76a4.png)

**Comment by adietish** [comment]
@robstryker this bug still exists, want to fix it in devex #168?

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/404

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/404  merged
