### ISSUE TITLE
When launching a server vscode-adapter should show "Output" tab and select the server from combo 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#208]
steps:

1. ASSERT: have a server defined and stopped in vscode (ex. wildfly 14)
1. EXEC: start this server

Result:
The server turns to ```(Started)``` but if it fails, it turns back to ```(Stopped)```. To see why I have to activate the "OUTPUT" tab and select the entry for my server in the combo which lists the available outputs:
![image](https://user-images.githubusercontent.com/25126/51843706-de279e80-2313-11e9-84fa-4876dddc00c4.png)

Expected:
The server turns to ```(Started)``` and the "OUTPUT" tab is activated and within it the entry for my server in the combo that lists the available outputs

**Comment by adietish** [comment]
@robstryker @jeffmaury thoughts?

**Comment by dgolovin** [comment]
@adietish it is already there in settings, you can enable vscode output channel activation when rspclient gets notifications about server has new lines in output stream.

**Comment by adietish** [comment]
@dgolovin thx for the pointer. So we use ```false``` by default, what's the reasoning? If I think that we should use ```true``` as default, am I missing something?

**Comment by robstryker** [comment]
I would support this setting being 'true' by default and allowing a user to turn it off.

**Comment by adietish** [comment]
duplicate to #224

**Comment by adietish** [comment]
closing as duplicated by #224
