### ISSUE TITLE
Add handling for servers left started from a previous session

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-adapters#221]
Leaving a server running when exiting VSCode will mark it as stopped next time the extension is launched. The problem is, there is no way to work with the server, unless you manually kill the running process that keeps hogging the port.

This needs some kind of check when starting the server (like there is in devstudio) to at least set its state to started.

**Comment by lstocchi** [comment]
@jrichter1 I tried to replicate the error but it seems to me it has been solved ... if I start a server, then close vscode, process gets killed and if I reopen vscode I can run another server without any problem. Could you please check and tell me if you still have this issue?

**Comment by jeffmaury** [comment]
You're right, seems we're stopping all started servers when VSCode exists. This one can be closed upon @jrichter1 approval
