### ISSUE TITLE
Enable stop server action when server is starting

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-adapters#223]
Imagine the server gets stuck in starting state, for example when I click debug and then it keeps
```
Listening for transport dt_socket at address: xxx
```
so I change my mind. Now I can't even stop the server.

**Comment by dgolovin** [comment]
Good point, but if server's not started yet stop action most likely would not work.  We might nee 'Terminate/Kill Kerver' action than would just terminate the process.

**Comment by adietish** [comment]
we wont tackle this enhancement before the release. Postponing.

**Comment by adietish** [comment]
fully agree here, I also found myself stuck here and had to kill the server on the cmd-line instead of waiting for it to shut down after a timeout.

**Comment by adietish** [comment]
this was fixed in PR #349 which introduced a stop(force) aka "Terminate" in the context menu.
