### ISSUE TITLE
Show output channel is useless unless the server has produced some output

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-adapters#224]
The option to show server output should either be disabled until the server output channel has been created in the current session, or it should produce some info to the user,
Otherwise it just sits there, not doing anything.

**Comment by dgolovin** [comment]
There is no way to control state Enable/Disable for context menu item in VSCode, so this cannot be fixed.
As for 'producing some info for the user' it works straightforward right now, nothing shown in output means no output from server.

**Comment by adietish** [comment]
@dgolovin so we're good to go in simply setting ```showChannelOnServerOutput.default``` to true?

**Comment by dgolovin** [comment]
@adietish I mean we don't need to change anything for now.

**Comment by adietish** [comment]
@dgolovin I'd argue that by default things should be visible since you wont see any feedback for quite some time on ex. MacOS where rsp-server takes about 45secs to start.

**Comment by adietish** [comment]
> we might want to have another option popUpOnErrorOutput and it would make sense to have it set to true by default.

+1 on this, postponing this issue to after the release.

**Comment by adietish** [comment]
we decided not to do anything here but to go for #231 instead. 
Thus closing this issue.
