### ISSUE TITLE
Can't create an adapter for CDK

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-adapters#227]
This is the status of trying to create a CDK adapter:
```
Message=Received response 'server/createServer - (2)' in 9ms. data=Result: {
client.js:40
    "status": {
        "severity": 4,
        "pluginId": "org.jboss.tools.rsp.server",
        "code": 0,
        "message": "There are missing/invalid required attributes for server type org.jboss.tools.rsp.server.minishift.servertype.impl.CDKServerType@6cb8dad8"
    },
    "invalidKeys": [
        ":secure:server:minishift.username",
        ":secure:server:minishift.password"
    ]
}
```
Also, for some reason it doesn't even show an error at this point.

**Comment by adietish** [comment]
@robstryker dare to comment why we dont want to tackle this before releasing?

**Comment by robstryker** [comment]
Jeff's patch for multiple required attributes should fix this.

**Comment by adietish** [comment]
@jrichter1 @robstryker Jeffs patch for issue #66 (PR #230) fixed this.

![image](https://user-images.githubusercontent.com/25126/52220733-df227800-289f-11e9-8d4d-09f45a454178.png)

I can create a cdk adapter and start it.

**Comment by adietish** [comment]
this is related to #66

**Comment by adietish** [comment]
There output that is produce in the **OUTPUT** terminal is printed 4x though: #233

**Comment by adietish** [comment]
Closing since one can now create a CDK adapter and start it.
