### ISSUE TITLE
Allow users to download runtimes

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#237]

**Comment by adietish** [comment]
this is the UI part for https://github.com/redhat-developer/rsp-server/pull/188

**Comment by robstryker** [comment]
EAP part is here:  dda2787b1e1f70977630e4d8a0bb4a1c1ede3804

**Comment by robstryker** [comment]
* ed6f02c - Implement dlrt for EAP (27 hours ago) <Rob Stryker>

**Comment by robstryker** [comment]
I'd say the main workflow here is done and any new issues or bug fixes should get their own issue.
