### ISSUE TITLE
Show Output Channel throw error when there is nothing to select.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-adapters#250]
<img width="535" alt="screenshot 2019-02-25 at 8 09 58 pm" src="https://user-images.githubusercontent.com/9924513/53344758-79268f00-3939-11e9-93bd-22a08515911d.png">

**Comment by adietish** [comment]
@mohitsuman can you please provide steps to reproduce this?

**Comment by robstryker** [comment]
Good safe patch.
