### ISSUE TITLE
Why we are throwing error if I don't want to select or add any server?

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-adapters#252]
<img width="291" alt="screenshot 2019-02-26 at 4 47 46 pm" src="https://user-images.githubusercontent.com/9924513/53409273-83529700-39e6-11e9-9f6b-151be181e32a.png">

**Comment by robstryker** [comment]
Steps to replicate please?

**Comment by robstryker** [comment]
In progress

**Comment by sudhirverma** [comment]
Steps:
1. click on Add Server Location.
2. don't select anything and press escape key `it will throw an error than`

**Comment by robstryker** [comment]
Fixed * 038417d - [252] Showing error if user cancels new server creation (26 hours ago) <Rob Stryker>
