### ISSUE TITLE
have no means to know what type a server is

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#290]
Once I created a server I have no way to know about the type (and other settings) of a server

**Comment by adietish** [comment]
* a basic way would be to include it in the label. But the label's already quite crowded: the server and deployment states are already present in 2 parenthesis:
![image](https://user-images.githubusercontent.com/25126/55714071-3d7bec00-59f2-11e9-809b-7454b773c0ff.png)
* another possibility could be to have them a child items of the servers. But there too, we already display deployments as children.

The only option I see left is to display them in an editor. @dgolovin @jrichter1 thoughts?

**Comment by jeffmaury** [comment]
What about having a new command like 'Get info' that would display server extended info in a terminal

**Comment by adietish** [comment]
@jeffmaury good idea, prefer that to an editor which usually is all about editing (exceptions exists of course ex. the kubernetes wizard of the microsoft kube extension)

**Comment by adietish** [comment]
We could of course also allow editing the settings which make sense (ex. runtime directory or deployable path) in an editor

**Comment by jrichter1** [comment]
As a bonus you can have different icons for server types or include server type in the tooltip.

**Comment by adietish** [comment]
@jrichter1 yes, true, we should also provide icons. Filing: #292
