### ISSUE TITLE
Error when server name contains special characters

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-adapters#298]
If you create a new server and use special chars in its name ( e.g: name&%$£"' ) you get this error "Could not save server to ...... ". We should sanitize the name deleting invalid chars or notify the user somehow.

**Comment by robstryker** [comment]
Tested this with the raw api / CLI (ie not in vscode), and got the following result:

add server
Please select a server type:
[ trimmed for brevity ]
etcetc
16) org.jboss.ide.eclipse.as.wildfly.100
etcetc


16
Please choose a unique name: 

name&%$£"'
Key: server.home.dir
Type: java.lang.String
Description: A filesystem path pointing to a server installation's root directory
Please enter a value: 

/home/rob/apps/jboss/unzipped/wildfly-10.0.0.Final.zip.expanded/
Key: vm.install.path
Type: java.lang.String
Description: A string representation pointing to a java home. If not set, java.home will be used instead.
Would you like to set this value? [y/n]

n
Skipping
Adding Server...
Server added: org.jboss.ide.eclipse.as.wildfly.100:name&%$£"'
Server Added

Of course trying to START the server failed horrificly.   So two questions:
1) On the vscode side, what exactly is causing the add-server error you are seeing?
2) On the rsp-server side, what is causing it to not start properly? I'd assume the quotes

**Comment by robstryker** [comment]
Answer to question 2)   Seems the only place the server name is used is when we pass in  -Dprogram.name=rsp:name&%$£"' 

So... problem is easily fixed by escaping quotes there.

**Comment by robstryker** [comment]
For item 2) I opened a PR on the server itself:  https://github.com/redhat-developer/rsp-server/pull/299

**Comment by lstocchi** [comment]
@robstryker I investigated a little bit more and i think we may have problems with limitations imposed by OS. In my case i did some tests on Windows where i cannot use chars like \ / : * ? " < > | to name a file. If i type \ in the server name i got an error "Could not save server to file C:\Users\Luca\.org.jboss.rsp.data\servers\ {name with \}". 

While in vscode-adapters the treeview gets updated with the new server, it doesn't get created on filesystem so i will never be able to get it started.

I don't know if this is a real issue because i think a normal person would never use such a letters in the name of a server but this is what i found. 

We should atleast prevent vscode-adapters to list these ghost server. Don't know if checking while the user type the name on vscode-adapters or check it in rsp-server before the creation or both...

**Comment by jeffmaury** [comment]
Either we should reject such names or if we accept them we should normalize when mapping to a path on the rsp-server side

**Comment by robstryker** [comment]
> If i type \ in the server name i got an error "Could not save server to file C:\Users\Luca.org.jboss.rsp.data\servers\ {name with }".

Are you able to get me a stacktrace on this? 

Ideally, if an error occurs creating the server on the RSP, then the CreateServerResponse should include that error and refuse to 'add' the server. So a stacktrace here would help a LOT, if possible. It's possible this error isn't being caught. 

I'm OK with teh solution of leaving it up to the filesystem, and a rejection is issued when the createServer request goes through, so long as everything is cleaned up ok. On the other hand, we could also come up with a regex we are ok with for validating server names.  I suppose we could limit it to [a-zA-Z0-9 ] ?  should that be enough?  We could add that restriction easily enough.

**Comment by lstocchi** [comment]
@robstryker i should have expressed myself better. The error is already caught up in rsp-server (i attached the stacktrace below so you can see), the issue is in vscode-adapters because the user is able to see the new server in the treeview even though it wasn't created by rsp-server (if you restart vscode-adapters, the "new server" disappear from the treeview, so the behavior is correct). 

Currently the user doesn't even know the reason (atleast not a detailed one) why its server wasn't created, we only display a generic error ("Could not save server to file ....") so my question was related to this. Wouldn't it be better to force the user to use a limited set of letters to prevent it? It makes sense to me to limit it to [a-zA-Z0-9].

In my previous job we worked with hackers so we had an obsessive-compulsive disorder filtering/sanitizing all kind of user input to prevent xss/sql attacks. This is where all my craziness comes from .... sorry :)

BTW i just wrote up to discuss it together, if you think the info currently displayed is enough for our purpose we can close this issue.

Below the stacktrace 
`Daemon Thread [ForkJoinPool.commonPool-worker-0] (Suspended (breakpoint at line 307 in Base))	
	Server(Base).saveToFile(IProgressMonitor) line: 307	
	Server.save(IProgressMonitor) line: 173	
	ServerModel.createServerUnprotected(String, String, Map<String,Object>) line: 248	
	ServerModel.createServer(String, String, Map<String,Object>) line: 214	
	ServerManagementServerImpl.createServerSync(ServerAttributes) line: 322	
	ServerManagementServerImpl.lambda$11(ServerAttributes) line: 309	
	1415813011.get() line: not available	
	ServerManagementServerImpl.lambda$24(RSPClient, CompletableFuture, Supplier) line: 601	
	1514754182.run() line: not available	
	CompletableFuture$AsyncRun.run() line: not available	
	CompletableFuture$AsyncRun.exec() line: not available	
	CompletableFuture$AsyncRun(ForkJoinTask<V>).doExec() line: not available	
	ForkJoinPool$WorkQueue.runTask(ForkJoinTask<?>) line: not available	
	ForkJoinPool.runWorker(ForkJoinPool$WorkQueue) line: not available	
	ForkJoinWorkerThread.run() line: not available	`

The error is already caught because it occurs in line 305 Files.write(file.toPath(), bytes); Server(Base).saveToFile(IProgressMonitor) line: 305

**Comment by robstryker** [comment]
Fixed already
