### ISSUE TITLE
add deployment: suggest to use an extension which specifies the type of deployment

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#305]
steps:
1. EXEC: add a deployment to your server
1. EXEC: pick a war or an exploded deployment
1. ASSERT: you're asked if you want to edit optional deployment parameters
1. EXEC: answer Yes  
1. ASSERT: you're asked to provide a deployment name
![image](https://user-images.githubusercontent.com/25126/57078664-f5996d80-6cee-11e9-8705-40995a44d2bd.png)

Result:
There's no indication that one should use an extension (suffix) that matches the type of deployment (ex. war)

Expected:
The label should suggest to use an extension that specifies the type of deployment (.war, .ear)

**Comment by adietish** [comment]
this should be filed and solved in rsp-server

**Comment by lstocchi** [comment]
Solved in rsp-server https://github.com/redhat-developer/rsp-server/pull/333
