### ISSUE TITLE
downloadable runtimes should be sorted in a natural way

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#309]
steps:
1. EXE: get to the list of downloadable runtimes (Create a server -> "Download runtime?": Yes, or "Download Server" in context menu)
![image](https://user-images.githubusercontent.com/25126/57154872-36ba7c00-6dda-11e9-9024-2ac00281751b.png)

Result:
Sorting of Wildfly servers should be in a natural sorting order: WildFly 8, 9, 10, 11, currently it's WildFly 10, 11, 12, 13, 14, 15, 16, 8,

**Comment by adietish** [comment]
for documentation purposes: like in java, there's a collator that sorts numeric strings in natural ordering: https://stackoverflow.com/questions/2802341/javascript-natural-sort-of-alphanumerical-strings

**Comment by robstryker** [comment]
I dislike that this was fixed on the client side. This should have been fixed on the server side if possible.
