### ISSUE TITLE
Error "Connection is closed" wont tell the user what exactly and why it failed

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#313]
steps: 
1. ASSERT: have extension (and server) running
1. EXEC: kill server (felix)
1. EXEC: Try to add local/download server

Result:
![image](https://user-images.githubusercontent.com/25126/57218984-0bf93f00-6ff7-11e9-9c47-9045210292f9.png)

Expected result:
The error should repeat the operation that failed and state the cause. It could say something like "Could not create a server, extension backend could not be contacted"
We should possibly also display a dialog when the rsp-server dies unexpectedly (and not just error when an operation is invoked).

This is related to #313 
This is related to #176

**Comment by odockal** [comment]
There is a very similar situation when an error is thrown but it won't bring much info to the user. One can check on #341 which introduces an error but user can just guess what went wrong:

![Screenshot_20190517_170947](https://user-images.githubusercontent.com/19164299/57937636-99297700-78c6-11e9-8795-02dce27055a0.png)

**Comment by adietish** [comment]
@odockal that situation reflects the poor reporting that we currently have. This PR here would improve the situation slightly:
![image](https://user-images.githubusercontent.com/25126/58083553-80b4a780-7bb9-11e9-8a21-114c67e3f6d5.png)
Nevertheless it's the server that needs to improve its message so that it gets evident why the deployment could not be added.
