### ISSUE TITLE
[critical] add deployment for zipped files impossible on windows

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/vscode-adapters#318]
On windows, the file-picker dialog can only open either in file mode or folder mode. Despite hte API allowing flags to allow each of file or folder, and despite this working fine on other OSes, it does not work on windows. 

Windows can currently only pick folders. This isn't good. 

Possible solutions:
1) Have two separate actions (add file deployment, add exploded deployment) to initiate two similar workflows but exchange the file picker dialog properly
2) Keep just the one action, but present the user with a quickpick to indicate before the dialog appears whether they want to pick a file or a folder. 

This is pretty bad, and our QE somehow missed it.

**Comment by robstryker** [comment]
https://vshaxe.github.io/vscode-extern/vscode/OpenDialogOptions.html

Options to configure the behaviour of a file open dialog.

    Note 1: A dialog can select files, folders, or both. This is not true for Windows which enforces to open either files or folder, but not both.
    Note 2: Explicitly setting canSelectFiles and canSelectFolders to false is futile and the editor then silently adjusts the options to select files.

**Comment by adietish** [comment]
we should show the quickpick (option 2) only on windows.
