### ISSUE TITLE
failed to attach to remote debuggee VM

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#328]
this depends on #126 
steps:
1. ASSERT: have a wildlfy server **(Stopped)** without deployment
1. ASSERT: have "kitchensink" (https://github.com/wildfly/quickstart/) in your workspace
1. EXEC: pick "Debug" in server context menu
1. ASSERT: get prompted "select the project you want to debug"
1. EXEC: select "kitchensink"
1. ASSERT: "Debug" perspective is opened
1. EXEC:  switch to "Explorer" perspective and stop the server (once it's fully started)
1. EXEC: once server is stopped pick "Debug"
1. EXEC: select "kitchensink" when you're prompted to select a project to debug

Result:
![image](https://user-images.githubusercontent.com/25126/57727238-4155fa80-7691-11e9-820b-a681ad2a76f2.png)
If you hit "Cancel" you can get hack to "Explorer" perspective and see that the server is stuck in **"(Starting)"**. After some timeout the server is back to **"(Stopped)"**

**Comment by lstocchi** [comment]
after removing the step where we make the user select the project he wants to debug, i cannot replicate this error. Could you please check it again?

**Comment by lstocchi** [comment]
The only problem i see is that even if we stop the server, the debug session still is running.

**Comment by adietish** [comment]
@lstocchi me neither, I can't replicate this in the latest code (that's not asking for the project any more). But yes, I see the debug session being kept, too. But then, this would be a different issue to file I think.
Closing as INVALID (since I can't replicate it any more)
