### ISSUE TITLE
Should be able to see that the server is currently debugging 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#333]
Steps:

1. ASSERT: have a stopped server
1. EXEC: pick "Debug" in the ctx menu

Result:
server turns (Starting) and then (Started) once it's all up. I have no hint that it's currently debugging 

Expected result:
I should be able to see that the server is currently debugging and would hit breakpoints that I set in my code.

**Comment by adietish** [comment]
quoting @robstryker 
> i think vscode side should have enough info to do this
> since the vscode side actually connected the debugger

**Comment by robstryker** [comment]
good point
