### ISSUE TITLE
get prompted to pick a deployment type on Mac (should only on Windows)

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#337]
follows up on #318 

steps:

1. ASSERT: have a wildfly server
1. EXEC: in ctx menu, pick “Add Deployment to Server”
1. ASSERT: dialog pops up to le you choose the file/directory

Result:
![image](https://user-images.githubusercontent.com/25126/57865477-ef7eb300-77fd-11e9-9980-59e37230f62c.png)
You're prompted to pick a deployment type.

Expected result:
You should only get prompted on Windows, neither on Linux nor on Mac.

**Comment by lstocchi** [comment]
@adietish I don't have a mac so i cannot test it but i think to know the problem. When you have some time could you please check what's the value returned by process.platform? It's darwin?
