### ISSUE TITLE
update change log and add release tag for the releases

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-adapters#340]
Regarding Server Connector release, we need to
1. update the changelog for the releases done.
2. Added release tag for a specific release to marketplace.

**Comment by robstryker** [comment]
* e63ae61 - (HEAD -> master, origin/master, origin/HEAD) [340] Update Changelog (7 seconds ago) <Rob Stryker>

Tag v0.15.3 is in repo now
