### ISSUE TITLE
Cannot choose a file in linux native dialog, folder only

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-adapters#341]
I am trying to deploy a war on the server but native linux dialog won't let me to choose single file. I can only choose a folder.

Env: vscode-adapters 0.15.3 from marketplace

**Comment by odockal** [comment]
1. Vscode with server connector installed and running on fedora 29
2. Create/Download a server
3. Start a server
4. Add deployment on server -> File search dialog is initiated
5. ASSERT: can choose a war
Actual result: cannot choose file but folders

**Comment by lstocchi** [comment]
Just tested on fedora 30 and i have the same issue.
It seems that in linux, options work differently than in Windows. If i set canSelectFiles to true and canSelectFolder to false I can still pick both files and folders but if i set both options to true i can only choose a folder ........

**Comment by adietish** [comment]
@lstocchi I think that we need a unit-test that asserts the flags as they're required by the different platforms. Dare to create one, please?

**Comment by robstryker** [comment]
Thought I had an issue with this solution, but it is fixed. This solution is good.
