### ISSUE TITLE
Set configuration file in wildfly server

### ISSUE THREAD

**Issue by toniperezfer** [redhat-developer/vscode-adapters#365]
Hi,

Is there a way to indicate in server configuration a configuration file?

Thanks

![Captura](https://user-images.githubusercontent.com/16151126/59349170-4605e100-8d19-11e9-8cd9-2f680e44ad76.PNG)

**Comment by adietish** [comment]
Hi @toniperezfer,
the screenshot was taken from JBoss Tools/Eclipse. You'd want the ability to set the configuration file in vscode, correct?

**Comment by toniperezfer** [comment]
Yeah, that's it.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/405

**Comment by robstryker** [comment]
Fixed
